# docker-compose -f ./local/redis.yml up -d
# docker exec -it my_redis redis-cli ping
version: '3.8'

services:
  redis:
    image: redis:7
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  redis_data: